# Generated by Django 5.2.4 on 2025-08-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_number', models.CharField(max_length=20, unique=True, verbose_name='Deklaratsiya raqami')),
                ('declaration_type', models.CharField(choices=[('import', 'Import'), ('export', 'Eksport'), ('transit', 'Tranzit')], max_length=20, verbose_name='Deklaratsiya turi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('submitted', 'Yuborildi'), ('under_review', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi'), ('completed', 'Bajarildi')], default='draft', max_length=20, verbose_name='Holat')),
                ('passport_series', models.CharField(max_length=2, verbose_name='Pasport seriyasi')),
                ('passport_number', models.CharField(max_length=7, verbose_name='Pasport raqami')),
                ('passport_issue_date', models.DateField(verbose_name='Pasport berilgan sana')),
                ('passport_expiry_date', models.DateField(verbose_name='Pasport amal qilish muddati')),
                ('passport_issuing_authority', models.CharField(max_length=200, verbose_name='Pasport bergan organ')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Aloqa qiluvchi shaxs')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Aloqa telefon raqami')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Aloqa email')),
                ('delivery_address', models.TextField(verbose_name='Yetkazish manzili')),
                ('delivery_country', models.CharField(max_length=100, verbose_name='Yetkazish davlati')),
                ('delivery_city', models.CharField(max_length=100, verbose_name='Yetkazish shahri')),
                ('product_name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('product_description', models.TextField(verbose_name='Mahsulot tavsifi')),
                ('product_quantity', models.PositiveIntegerField(verbose_name='Mahsulot miqdori')),
                ('product_unit', models.CharField(max_length=50, verbose_name="O'lchov birligi")),
                ('product_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Mahsulot qiymati')),
                ('product_currency', models.CharField(default='USD', max_length=3, verbose_name='Valyuta')),
                ('customs_code', models.CharField(blank=True, max_length=20, verbose_name='Bojxona kodi')),
                ('customs_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Bojxona qiymati')),
                ('customs_duty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Bojxona to'lovi")),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumotlar")),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin izohlari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan sana')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan sana")),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rad etish sababi')),
            ],
            options={
                'verbose_name': 'Deklaratsiya',
                'verbose_name_plural': 'Deklaratsiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeclarationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Hisob-faktura'), ('packing_list', "O'rash ro'yxati"), ('certificate', 'Sertifikat'), ('permit', 'Ruxsatnoma'), ('other', 'Boshqa')], max_length=20, verbose_name='Hujjat turi')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('file', models.FileField(upload_to='declaration_documents/', verbose_name='Fayl')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Deklaratsiya hujjati',
                'verbose_name_plural': 'Deklaratsiya hujjatlari',
            },
        ),
        migrations.CreateModel(
            name='DeclarationStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('submitted', 'Yuborildi'), ('under_review', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi'), ('completed', 'Bajarildi')], max_length=20, verbose_name='Holat')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Deklaratsiya holati yangilanishi',
                'verbose_name_plural': 'Deklaratsiya holati yangilanishlari',
                'ordering': ['-updated_at'],
            },
        ),
    ]
