# Generated by Django 5.2.4 on 2025-08-04 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('declarations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_declarations', to=settings.AUTH_USER_MODEL, verbose_name="Ko'rib chiqgan foydalanuvchi"),
        ),
        migrations.AddField(
            model_name='declaration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='declarationdocument',
            name='declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='declarations.declaration', verbose_name='Deklaratsiya'),
        ),
        migrations.AddField(
            model_name='declarationstatusupdate',
            name='declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='declarations.declaration', verbose_name='Deklaratsiya'),
        ),
        migrations.AddField(
            model_name='declarationstatusupdate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yangilagan foydalanuvchi'),
        ),
    ]
