# Generated by Django 5.2.4 on 2025-08-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Buyurtma raqami')),
                ('product_name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('product_description', models.TextField(blank=True, verbose_name='Mahsulot tavsifi')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdori')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birlik narxi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy narx')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('shipped', 'Yuborildi'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi'), ('returned', 'Qaytarildi')], default='pending', max_length=20, verbose_name='Holat')),
                ('delivery_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_transit', "Yo'lda"), ('out_for_delivery', 'Yetkazish uchun chiqdi'), ('delivered', 'Yetkazildi'), ('failed', 'Muvaffaqiyatsiz')], default='pending', max_length=20, verbose_name='Yetkazish holati')),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Izlash raqami')),
                ('tracking_url', models.URLField(blank=True, null=True, verbose_name='Izlash havolasi')),
                ('delivery_address', models.TextField(verbose_name='Yetkazish manzili')),
                ('delivery_phone', models.CharField(max_length=20, verbose_name='Yetkazish telefon raqami')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='Yetkazish izohlari')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma sanasi')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Taxminiy yetkazish sanasi')),
                ('actual_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Haqiqiy yetkazish sanasi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin izohlari')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Hisob-faktura'), ('receipt', 'Kvitansiya'), ('tracking', 'Izlash hujjati'), ('other', 'Boshqa')], max_length=20, verbose_name='Hujjat turi')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('file', models.FileField(upload_to='order_documents/', verbose_name='Fayl')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Buyurtma hujjati',
                'verbose_name_plural': 'Buyurtma hujjatlari',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('shipped', 'Yuborildi'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi'), ('returned', 'Qaytarildi')], max_length=20, verbose_name='Holat')),
                ('delivery_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_transit', "Yo'lda"), ('out_for_delivery', 'Yetkazish uchun chiqdi'), ('delivered', 'Yetkazildi'), ('failed', 'Muvaffaqiyatsiz')], max_length=20, verbose_name='Yetkazish holati')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Buyurtma holati yangilanishi',
                'verbose_name_plural': 'Buyurtma holati yangilanishlari',
                'ordering': ['-updated_at'],
            },
        ),
    ]
