# Generated by Django 5.2.4 on 2025-08-04 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('template_type', models.CharField(choices=[('verification', 'Tasdiqlash'), ('welcome', 'Xush kelibs'), ('password_reset', 'Parolni tiklash'), ('order_confirmation', 'Buyurtma tasdiqlash'), ('declaration_status', 'Deklaratsiya holati'), ('support_reply', "Qo'llab-quvvatlash javobi"), ('newsletter', 'Yangiliklar')], max_length=20, verbose_name='Shablon turi')),
                ('subject', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('html_content', models.TextField(blank=True, verbose_name='HTML kontent')),
                ('variables', models.JSONField(default=dict, verbose_name="O'zgaruvchilar")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Email shabloni',
                'verbose_name_plural': 'Email shablonlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('template_type', models.CharField(choices=[('declaration', 'Deklaratsiya'), ('invoice', 'Hisob-faktura'), ('receipt', 'Kvitansiya'), ('contract', 'Shartnoma'), ('report', 'Hisobot')], max_length=20, verbose_name='Shablon turi')),
                ('html_template', models.TextField(verbose_name='HTML shablon')),
                ('css_styles', models.TextField(blank=True, verbose_name='CSS stillar')),
                ('variables', models.JSONField(default=dict, verbose_name="O'zgaruvchilar")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'PDF shabloni',
                'verbose_name_plural': 'PDF shablonlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Kalit')),
                ('value', models.TextField(verbose_name='Qiymat')),
                ('setting_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('pdf', 'PDF'), ('general', 'Umumiy'), ('security', 'Xavfsizlik')], max_length=20, verbose_name='Sozlash turi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Tizim sozlamasi',
                'verbose_name_plural': 'Tizim sozlamalari',
                'ordering': ['setting_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Qabul qiluvchi')),
                ('subject', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xatolik'), ('bounced', 'Qaytarildi')], default='pending', max_length=20, verbose_name='Holat')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan sana')),
                ('error_message', models.TextField(blank=True, verbose_name='Xatolik xabari')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, verbose_name='Foydalanuvchi agenti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='utils.emailtemplate', verbose_name='Shablon')),
            ],
            options={
                'verbose_name': 'Email log',
                'verbose_name_plural': 'Email loglari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name="Fayl yo'li")),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fayl hajmi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('generated', 'Yaratildi'), ('failed', 'Xatolik')], default='pending', max_length=20, verbose_name='Holat')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Yaratilgan sana')),
                ('error_message', models.TextField(blank=True, verbose_name='Xatolik xabari')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='utils.pdftemplate', verbose_name='Shablon')),
            ],
            options={
                'verbose_name': 'PDF log',
                'verbose_name_plural': 'PDF loglari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xatolik'), ('delivered', 'Yetkazildi')], default='pending', max_length=20, verbose_name='Holat')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan sana')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Yetkazilgan sana')),
                ('error_message', models.TextField(blank=True, verbose_name='Xatolik xabari')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'SMS log',
                'verbose_name_plural': 'SMS loglari',
                'ordering': ['-created_at'],
            },
        ),
    ]
