# Generated by Django 5.2.4 on 2025-08-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': "Qo'llab-quvvatlash kategoriyasi",
                'verbose_name_plural': "Qo'llab-quvvatlash kategoriyalari",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('customer', 'Mijoz'), ('staff', 'Xodim'), ('system', 'Tizim')], default='customer', max_length=20, verbose_name='Xabar turi')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/', verbose_name='Ilova')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name="O'qilgan sana")),
            ],
            options={
                'verbose_name': "Qo'llab-quvvatlash xabari",
                'verbose_name_plural': "Qo'llab-quvvatlash xabarlari",
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('subject', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': "Qo'llab-quvvatlash shabloni",
                'verbose_name_plural': "Qo'llab-quvvatlash shablonlari",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='Tiket raqami')),
                ('subject', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('ticket_type', models.CharField(choices=[('general', 'Umumiy'), ('technical', 'Texnik'), ('billing', "To'lov"), ('order', 'Buyurtma'), ('declaration', 'Deklaratsiya'), ('other', 'Boshqa')], default='general', max_length=20, verbose_name='Tiket turi')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='medium', max_length=20, verbose_name='Ustuvorlik')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('in_progress', 'Jarayonda'), ('waiting_for_customer', 'Mijoz kutilmoqda'), ('resolved', 'Hal qilindi'), ('closed', 'Yopildi')], default='open', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan sana')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yopilgan sana')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin izohlari')),
            ],
            options={
                'verbose_name': "Qo'llab-quvvatlash tiketi",
                'verbose_name_plural': "Qo'llab-quvvatlash tiketlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
