# Generated by Django 5.2.4 on 2025-08-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': "Ko'p so'raladigan savol",
                'verbose_name_plural': "Ko'p so'raladigan savollar",
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('excerpt', models.TextField(blank=True, verbose_name='Qisqacha tavsif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Rasm')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr etilgan'), ('archived', 'Arxivlangan')], default='draft', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Nashr etilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta sarlavha')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta tavsif')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Yangilik kategoriyasi',
                'verbose_name_plural': 'Yangilik kategoriyalari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Xizmat nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Qisqacha tavsif')),
                ('service_type', models.CharField(choices=[('import', 'Import xizmati'), ('export', 'Eksport xizmati'), ('customs', 'Bojxona xizmati'), ('logistics', 'Logistika xizmati'), ('consulting', 'Maslahat xizmati'), ('other', 'Boshqa')], max_length=20, verbose_name='Xizmat turi')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Narx')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Valyuta')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/icons/', verbose_name='Ikonka')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('info_type', models.CharField(choices=[('about', 'Kompaniya haqida'), ('delivery', 'Yetkazish'), ('pricing', 'Narxlar'), ('faq', "Ko'p so'raladigan savollar"), ('contact', "Aloqa ma'lumotlari"), ('terms', 'Foydalanish shartlari'), ('privacy', 'Maxfiylik siyosati')], max_length=20, verbose_name="Ma'lumot turi")),
                ('content', models.TextField(verbose_name='Kontent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': "Kompaniya ma'lumoti",
                'verbose_name_plural': "Kompaniya ma'lumotlari",
                'ordering': ['order', 'title'],
                'unique_together': {('info_type', 'is_active')},
            },
        ),
    ]
