# Generated by Django 5.2.4 on 2025-08-04 18:21

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil rasmi')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('client_code', models.CharField(default=users.models.generate_client_code, max_length=10, unique=True, verbose_name='Mijoz kodi')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email tasdiqlangan')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='Telefon tasdiqlangan')),
                ('email_verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('phone_verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_code_expires', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Davlat')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Shahar')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Foydalanuvchi nomi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=2, verbose_name='Seriya')),
                ('number', models.CharField(max_length=7, verbose_name='Raqam')),
                ('issue_date', models.DateField(verbose_name='Berilgan sana')),
                ('expiry_date', models.DateField(verbose_name='Amal qilish muddati')),
                ('issuing_authority', models.CharField(max_length=200, verbose_name='Bergan organ')),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='passports/', verbose_name='Pasport rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Pasport',
                'verbose_name_plural': 'Pasportlar',
            },
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Pasport'), ('id_card', 'ID karta'), ('driving_license', 'Haydovchilik guvohnomasi'), ('other', 'Boshqa')], max_length=20, verbose_name='Hujjat turi')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Fayl')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi hujjati',
                'verbose_name_plural': 'Foydalanuvchi hujjatlari',
            },
        ),
    ]
